export default {
  /* user */
  USER_FETCH_LOGIN: "USER_FETCH_LOGIN",
  USER_FETCH_LOGIN_SUCCESS: "USER_FETCH_LOGIN_SUCCESS",
  USER_FETCH_LOGIN_ERROR: "USER_FETCH_LOGIN_ERROR",
  USER_FETCH_TRY_AUTO_LOGIN: "USER_FETCH_TRY_AUTO_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_CREATE_MOVIE_HISTORY: "USER_CREATE_MOVIE_HISTORY",
  USER_CREATE_MOVIE_HISTORY_SUCCESS: "USER_CREATE_MOVIE_HISTORY_SUCCESS",
  USER_CREATE_MOVIE_HISTORY_ERROR: "USER_CREATE_MOVIE_HISTORY_ERROR",
  USER_CREATE_MOVIE_BOOKMARK: "USER_CREATE_MOVIE_BOOKMARK",
  USER_CREATE_MOVIE_BOOKMARK_SUCCESS: "USER_CREATE_MOVIE_BOOKMARK_SUCCESS",
  USER_CREATE_MOVIE_BOOKMARK_ERROR: "USER_CREATE_MOVIE_BOOKMARK_ERROR",
  USER_REMOVE_MOVIE_BOOKMARK: "USER_REMOVE_MOVIE_BOOKMARK",
  USER_REMOVE_MOVIE_BOOKMARK_SUCCESS: "USER_REMOVE_MOVIE_BOOKMARK_SUCCESS",
  USER_REMOVE_MOVIE_BOOKMARK_ERROR: "USER_REMOVE_MOVIE_BOOKMARK_ERROR",

  /* MOVIE */
  MOVIE_FETCH: "MOVIE_FETCH",
  MOVIE_FETCH_SUCCESS: "MOVIE_FETCH_SUCCESS",
  MOVIE_FETCH_ERROR: "MOVIE_FETCH_ERROR",
  MOVIE_COLLECTION_FETCH: "MOVIE_COLLECTION_FETCH",
  MOVIE_COLLECTION_FETCH_SUCCESS: "MOVIE_COLLECTION_FETCH_SUCCESS",
  MOVIE_COLLECTION_FETCH_ERROR: "MOVIE_COLLECTION_FETCH_ERROR",
  MOVIE_CLEAR_SELECTED: "MOVIE_CLEAR_SELECTED",

  /* SEARCH */
  SEARCH_SUGGESTION_FETCH: "SEARCH_SUGGESTION_FETCH",
  SEARCH_SUGGESTION_FETCH_SUCCESS: "SEARCH_SUGGESTION_FETCH_SUCCESS",
  SEARCH_SUGGESTION_FETCH_ERROR: "SEARCH_SUGGESTION_FETCH_ERROR",
  SEARCH_MOVIE_FETCH: "SEARCH_MOVIE_FETCH",
  SEARCH_MOVIE_FETCH_SUCCESS: "SEARCH_MOVIE_FETCH_SUCCESS",
  SEARCH_MOVIE_FETCH_ERROR: "SEARCH_MOVIE_FETCH_ERROR",
  SEARCH_MOVIE_RESULT_CLEAR: "SEARCH_MOVIE_RESULT_CLEAR",
  SEARCH_SUGGESTION_CLEAR: "SEARCH_SUGGESTION_CLEAR",

  /* ERROR */
  ERROR_CREATE: "ERROR_CREATE",
  ERROR_ALL_CLEAR: "ERROR_ALL_CLEAR"
};
