export default {
  /* user */
  USER_FETCH_LOGIN: "USER_FETCH_LOGIN",
  USER_FETCH_LOGIN_SUCCESS: "USER_FETCH_LOGIN_SUCCESS",
  USER_FETCH_LOGIN_ERROR: "USER_FETCH_LOGIN_ERROR",
  USER_FETCH_TRY_AUTO_LOGIN: "USER_FETCH_TRY_AUTO_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",

  /* MOVIE */
  CLEAR_SELECTED_MOVIE: "CLEAR_SELECTED_MOVIE",
  MOVIE_SEARCH_RESULT_CLEAR: "MOVIE_SEARCH_RESULT_CLEAR",
  MOVIE_FETCH: "MOVIE_FETCH",
  MOVIE_FETCH_SUCCESS: "MOVIE_FETCH_SUCCESS",
  MOVIE_FETCH_ERROR: "MOVIE_FETCH_ERROR",
  MOVIE_COLLECTION_FETCH: "MOVIE_COLLECTION_FETCH",
  MOVIE_COLLECTION_FETCH_SUCCESS: "MOVIE_COLLECTION_FETCH_SUCCESS",
  MOVIE_COLLECTION_FETCH_ERROR: "MOVIE_COLLECTION_FETCH_ERROR",

  /* ERROR */
  ERROR_CREATE: "ERROR_CREATE",
  ERROR_ALL_CLEAR: "ERROR_ALL_CLEAR"
};
