export default {
  FETCH_SEARCH: "FETCH_SEARCH",
  FETCH_UPCOMING: "FETCH_UPCOMING",
  FETCH_POPULAR: "FETCH_POPULAR",
  FETCH_TOPRATED: "FETCH_TOPRATED",
  FETCH_NOWPLAYING: "FETCH_NOWPLAYING",
  FETCH_THEMOVIE: "FETCH_THEMOVIE",
  FETCH_CASTLIST: "FETCH_CASTLIST",
  FETCH_ERROR: "FETCH_ERROR"
};
