export default {
  FETCH_UPCOMING: "FETCH_UPCOMING",
  FETCH_POPULAR: "FETCH_POPULAR",
  FETCH_TOPRATED: "FETCH_TOPRATED",
  FETCH_NOWPLAYING: "FETCH_NOWPLAYING",

  FETCH_SEARCH: "FETCH_SEARCH",
  FETCH_THEMOVIE: "FETCH_THEMOVIE",
  FETCH_CASTLIST: "FETCH_CASTLIST",

  CLEAR_THE_MOVIE: "CLEAR_THE_MOVIE",
  CLEAR_SEARCH_RESULT: "CLEAR_SEARCH_RESULT",

  FETCH_TMDBAPI_ERROR: "FETCH_TMDBAPI_ERROR"
};
